### ISSUE TITLE
Need Example of using idle:stop

### ISSUE THREAD

**Issue by mubasherusman** [kidh0/jquery.idle#20]
How to use "idle:stop" when we I allredy has idle:10000 registered. 

`$(document).idle({

```
  onIdle: function(){
    $('#status').toggleClass('idle').html('Idle!');
  },idle: 2000,
  keepTracking: true
});` 
```

**Comment by moisesnandres** [comment]
Add the event 'idle:stop' to your document
`$(document).trigger('idle:stop');`

**Comment by kmanolis** [comment]
Wondering the same 2-3 days ago, and came to answer, but i see it is already answered.

Also i would like to add something.
It is advisable to add namespaces at events in order to prevent to stop any other event which you may have already defined.

E.g. If you have:
`$(document).on('click','.element',(function() { /*something*/ }));`

And you have this too
```
$(document).idle({
	onIdle: function(){
	},
	onActive: function(){
	},
	events: 'click mousover',
	idle: 2000
});
```
and you stop the idle plugin using:
`$(document).trigger("idle:stop");`

Then the first code would break too.
So at my example, you should change `events: 'click mousover',` to `events: 'click.mynamespace mousover.mynamespace',`
