### ISSUE TITLE
jquery dependency missing from package.json

### ISSUE THREAD

**Issue by hauntingEcho** [kidh0/jquery.idle#31]

**Comment by kidh0** [comment]
Fixed.

**Comment by hauntingEcho** [comment]
thanks for responding so quickly!  It looks like that commit removed the package.json file entirely though?

**Comment by kidh0** [comment]
My bad, it's up and running again ;)

**Comment by hauntingEcho** [comment]
thanks!

**Comment by davejamesmiller** [comment]
I think this should be a [peerDependency](https://nodejs.org/en/blog/npm/peer-dependencies/) - otherwise it installs its own local copy of jQuery, which isn't needed and doesn't play nicely with Webpack.

```js
import $ from 'jquery';
import 'imports-loader?jQuery=jquery$!jquery.idle';

$(document).idle({ ... }); // TypeError: (...).idle is not a function
```

This is because the plugin loads one copy of jQuery (the one npm installed in `node_modules/jquery.idle/node_modules/jquery/`), while the applications loads a different copy (the one installed in `node_modules/jquery/`).

**Comment by davejamesmiller** [comment]
Thanks @kidh0, that works great. 👍
